name: BarotraumaModdingFramework
recipe: symfony
config:
  webroot: web
  via: nginx
services:
  # @todo: Rename docker container ID "appserver_1" to something better.
  appserver:
    type: php:8.1
    overrides:
      # Integration.
      volumes:
        - 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma:/app/Modding/Barotrauma'
        - 'C:\Users\Win10_Game_OS\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed:/app/Modding/Workshop'
        - 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\LocalMods:/app/Modding/LocalMods'
      # Image with Lando PHP 8.1 and SteamCMD.
      image: azumasv/barotraumix:lando-php-8.1
      environment:
        BMF_PATH_FRAMEWORK: /app/Framework
        BMF_PATH_GAME: /app/Modding/Barotrauma
        BMF_PATH_WORKSHOP: /app/Modding/Workshop
        BMF_PATH_INPUT: /app/Modding/ModSources
        BMF_PATH_OUTPUT: /app/Modding/LocalMods